version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '9432:5432'
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '9379:6379'

# CURRENTLY DOESN'T WORK!
  backend:
    build:
      context: .
      dockerfile: backend/backend.dockerfile
    env_file:
      - backend/backend.env
    ports:
      - '9080:8080'
    volumes:
      - ./backend:/backend:cached
    depends_on:
      - db
      - redis
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/frontend.dockerfile
    ports:
      - '9090:8090'
    volumes:
      - ./frontend:/frontend:cached
      - /frontend/node_modules

  nginx:
    image: nginx:1.25.2
    ports:
      - '9000:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - backend
      - frontend