"""update_schema

Revision ID: 311f430247b0
Revises: e42090c2bffa
Create Date: 2023-12-03 21:20:42.766980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '311f430247b0'
down_revision: Union[str, None] = 'e42090c2bffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_in_garage',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('car_gen_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_gen_id'], ['car_gen.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'car_gen_id')
    )
    op.create_index(op.f('ix_car_in_garage_created_at'), 'car_in_garage', ['created_at'], unique=False)
    op.drop_index('ix_detail_created_at', table_name='detail')
    op.drop_index('ix_car_created_at', table_name='car')
    op.drop_index('ix_garage_created_at', table_name='garage')
    op.add_column('product', sa.Column('car_gen_id', sa.BigInteger(), nullable=False))
    op.add_column('product', sa.Column('detail_type_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('product_car_id_fkey', 'product', type_='foreignkey')
    op.drop_constraint('product_detail_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'car_gen', ['car_gen_id'], ['id'])
    op.create_foreign_key(None, 'product', 'detail_type', ['detail_type_id'], ['id'])
    op.drop_column('product', 'detail_id')
    op.drop_column('product', 'car_id')
    op.drop_table('garage')
    op.drop_table('detail')
    op.drop_table('car')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('car_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('detail_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_detail_id_fkey', 'product', 'detail', ['detail_id'], ['id'])
    op.create_foreign_key('product_car_id_fkey', 'product', 'car', ['car_id'], ['id'])
    op.drop_column('product', 'detail_type_id')
    op.drop_column('product', 'car_gen_id')
    op.create_table('garage',
    sa.Column('profile_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('car_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], name='garage_car_id_fkey'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name='garage_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='garage_pkey'),
    sa.UniqueConstraint('profile_id', 'car_id', name='garage_profile_id_car_id_key')
    )
    op.create_index('ix_garage_created_at', 'garage', ['created_at'], unique=False)
    op.create_table('car',
    sa.Column('car_brand_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('car_model_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('car_gen_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['car_brand_id'], ['car_brand.id'], name='car_car_brand_id_fkey'),
    sa.ForeignKeyConstraint(['car_gen_id'], ['car_gen.id'], name='car_car_gen_id_fkey'),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_model.id'], name='car_car_model_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='car_pkey'),
    sa.UniqueConstraint('car_brand_id', 'car_model_id', 'car_gen_id', name='car_car_brand_id_car_model_id_car_gen_id_key')
    )
    op.create_index('ix_car_created_at', 'car', ['created_at'], unique=False)
    op.create_table('detail',
    sa.Column('detail_category_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('detail_type_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['detail_category_id'], ['detail_category.id'], name='detail_detail_category_id_fkey'),
    sa.ForeignKeyConstraint(['detail_type_id'], ['detail_type.id'], name='detail_detail_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='detail_pkey'),
    sa.UniqueConstraint('detail_category_id', 'detail_type_id', name='detail_detail_category_id_detail_type_id_key')
    )
    op.create_index('ix_detail_created_at', 'detail', ['created_at'], unique=False)
    op.drop_index(op.f('ix_car_in_garage_created_at'), table_name='car_in_garage')
    op.drop_table('car_in_garage')
    # ### end Alembic commands ###
