"""add_core_tables

Revision ID: 3cc4e55b2435
Revises: 810fae843500
Create Date: 2023-10-13 03:07:18.710657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc4e55b2435'
down_revision: Union[str, None] = '810fae843500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_brand',
    sa.Column('brand_name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_brand_brand_name'), 'car_brand', ['brand_name'], unique=True)
    op.create_index(op.f('ix_car_brand_created_at'), 'car_brand', ['created_at'], unique=False)
    op.create_table('detail_category',
    sa.Column('category_name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detail_category_category_name'), 'detail_category', ['category_name'], unique=True)
    op.create_index(op.f('ix_detail_category_created_at'), 'detail_category', ['created_at'], unique=False)
    op.create_table('car_model',
    sa.Column('car_brand_id', sa.BigInteger(), nullable=False),
    sa.Column('model_name', sa.String(length=30), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_brand_id'], ['car_brand.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_brand_id', 'model_name')
    )
    op.create_index(op.f('ix_car_model_created_at'), 'car_model', ['created_at'], unique=False)
    op.create_index(op.f('ix_car_model_model_name'), 'car_model', ['model_name'], unique=False)
    op.create_table('detail_type',
    sa.Column('detail_category_id', sa.BigInteger(), nullable=False),
    sa.Column('type_name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detail_category_id'], ['detail_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detail_category_id', 'type_name')
    )
    op.create_index(op.f('ix_detail_type_created_at'), 'detail_type', ['created_at'], unique=False)
    op.create_index(op.f('ix_detail_type_type_name'), 'detail_type', ['type_name'], unique=False)
    op.create_table('car_gen',
    sa.Column('car_model_id', sa.BigInteger(), nullable=False),
    sa.Column('gen_name', sa.String(length=60), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_model_id', 'gen_name')
    )
    op.create_index(op.f('ix_car_gen_created_at'), 'car_gen', ['created_at'], unique=False)
    op.create_index(op.f('ix_car_gen_gen_name'), 'car_gen', ['gen_name'], unique=True)
    op.create_table('detail',
    sa.Column('detail_category_id', sa.BigInteger(), nullable=False),
    sa.Column('detail_type_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detail_category_id'], ['detail_category.id'], ),
    sa.ForeignKeyConstraint(['detail_type_id'], ['detail_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detail_category_id', 'detail_type_id')
    )
    op.create_index(op.f('ix_detail_created_at'), 'detail', ['created_at'], unique=False)
    op.create_table('car',
    sa.Column('car_brand_id', sa.BigInteger(), nullable=False),
    sa.Column('car_model_id', sa.BigInteger(), nullable=False),
    sa.Column('car_gen_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_brand_id'], ['car_brand.id'], ),
    sa.ForeignKeyConstraint(['car_gen_id'], ['car_gen.id'], ),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_brand_id', 'car_model_id', 'car_gen_id')
    )
    op.create_index(op.f('ix_car_created_at'), 'car', ['created_at'], unique=False)
    op.create_table('garage',
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('car_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'car_id')
    )
    op.create_index(op.f('ix_garage_created_at'), 'garage', ['created_at'], unique=False)
    op.create_table('product',
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'USED', name='productcondition'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('car_id', sa.BigInteger(), nullable=False),
    sa.Column('detail_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['detail_id'], ['detail.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_created_at'), 'product', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_published_at'), 'product', ['published_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_published_at'), table_name='product')
    op.drop_index(op.f('ix_product_created_at'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_garage_created_at'), table_name='garage')
    op.drop_table('garage')
    op.drop_index(op.f('ix_car_created_at'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_detail_created_at'), table_name='detail')
    op.drop_table('detail')
    op.drop_index(op.f('ix_car_gen_gen_name'), table_name='car_gen')
    op.drop_index(op.f('ix_car_gen_created_at'), table_name='car_gen')
    op.drop_table('car_gen')
    op.drop_index(op.f('ix_detail_type_type_name'), table_name='detail_type')
    op.drop_index(op.f('ix_detail_type_created_at'), table_name='detail_type')
    op.drop_table('detail_type')
    op.drop_index(op.f('ix_car_model_model_name'), table_name='car_model')
    op.drop_index(op.f('ix_car_model_created_at'), table_name='car_model')
    op.drop_table('car_model')
    op.drop_index(op.f('ix_detail_category_created_at'), table_name='detail_category')
    op.drop_index(op.f('ix_detail_category_category_name'), table_name='detail_category')
    op.drop_table('detail_category')
    op.drop_index(op.f('ix_car_brand_created_at'), table_name='car_brand')
    op.drop_index(op.f('ix_car_brand_brand_name'), table_name='car_brand')
    op.drop_table('car_brand')
    # ### end Alembic commands ###
