"""add_score

Revision ID: 50b0aa9b2c66
Revises: c8529feabc29
Create Date: 2023-11-01 01:56:18.758456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b0aa9b2c66'
down_revision: Union[str, None] = 'c8529feabc29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_gen', sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_car_gen_score'), 'car_gen', ['score'], unique=False)
    op.add_column('car_model', sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_car_model_score'), 'car_model', ['score'], unique=False)
    op.add_column('detail_category', sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_detail_category_score'), 'detail_category', ['score'], unique=False)
    op.add_column('detail_type', sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_detail_type_score'), 'detail_type', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detail_type_score'), table_name='detail_type')
    op.drop_column('detail_type', 'score')
    op.drop_index(op.f('ix_detail_category_score'), table_name='detail_category')
    op.drop_column('detail_category', 'score')
    op.drop_index(op.f('ix_car_model_score'), table_name='car_model')
    op.drop_column('car_model', 'score')
    op.drop_index(op.f('ix_car_gen_score'), table_name='car_gen')
    op.drop_column('car_gen', 'score')
    # ### end Alembic commands ###
