"""change_profile

Revision ID: 810fae843500
Revises: 38467c890e96
Create Date: 2023-10-11 23:44:18.320870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810fae843500'
down_revision: Union[str, None] = '38467c890e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('profile', sa.Column('email', sa.String(length=30), nullable=False))
    op.add_column('profile', sa.Column('password_hash', sa.String(length=72), nullable=False))
    op.add_column('profile', sa.Column('is_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('profile', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint('profile_username_key', 'profile', type_='unique')
    op.create_unique_constraint(None, 'profile', ['email'])
    op.drop_column('profile', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'profile', type_='unique')
    op.create_unique_constraint('profile_username_key', 'profile', ['username'])
    op.drop_column('profile', 'is_admin')
    op.drop_column('profile', 'is_confirmed')
    op.drop_column('profile', 'password_hash')
    op.drop_column('profile', 'email')
    op.drop_column('profile', 'name')
    # ### end Alembic commands ###
