"""add_product_complaints

Revision ID: 88fcaf0093f7
Revises: 32e521bf5a6d
Create Date: 2023-12-18 22:13:22.717837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fcaf0093f7'
down_revision: Union[str, None] = '32e521bf5a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('complaints', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_product_complaints'), 'product', ['complaints'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_complaints'), table_name='product')
    op.drop_column('product', 'complaints')
    # ### end Alembic commands ###
