"""add_profile_fields

Revision ID: 9c0b0cfe13fb
Revises: 311f430247b0
Create Date: 2023-12-03 22:11:04.799537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0b0cfe13fb'
down_revision: Union[str, None] = '311f430247b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('phone', sa.String(length=12), nullable=False))
    op.add_column('profile', sa.Column('city', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'profile', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='unique')
    op.drop_column('profile', 'city')
    op.drop_column('profile', 'phone')
    # ### end Alembic commands ###
