"""add_car_brand_score

Revision ID: c8529feabc29
Revises: 3cc4e55b2435
Create Date: 2023-11-01 00:10:04.912284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8529feabc29'
down_revision: Union[str, None] = '3cc4e55b2435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_brand', sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_index('ix_car_brand_brand_name', table_name='car_brand')
    op.create_index(op.f('ix_car_brand_score'), 'car_brand', ['score'], unique=False)
    op.create_unique_constraint(None, 'car_brand', ['brand_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_brand', type_='unique')
    op.drop_index(op.f('ix_car_brand_score'), table_name='car_brand')
    op.create_index('ix_car_brand_brand_name', 'car_brand', ['brand_name'], unique=False)
    op.drop_column('car_brand', 'score')
    # ### end Alembic commands ###
